[project]
name = "kul-ocr"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[tool.uv.sources]
ocr-kul = { workspace = true }

[tool.uv.workspace]
members = ["."]
