[project]
name = "kul-ocr"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["pytesseract", "Pillow",]
packages = [{include = "ocr_kul", from = "src"}]

[dependency-groups]
dev = [
    "pyright>=1.1.407",
]
